import Head from "next/head";
import FeedbackForm from "../components/FeedbackForm";

export default function Home() {
  return (
    <div className="h-full w-full flex flex-col items-center text-slate-700 p-4">
      <Head>
        <title>Review Form | SCMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="./scms.png" alt="scms" className="h-52 w-52" />
      <p className="text-3xl font-extrabold mb-2">
        Welcome to <span className="text-blue-600">Science Exhibition</span>
      </p>

      <FeedbackForm />
    </div>
  );
}
